twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
    - 'bootstrap_3_horizontal_layout.html.twig'
    globals:
        google_map_key: '%env(GOOGLE_MAP_KEY)%'
